https://www.kaggle.com/datasets/kaggle/sf-salaries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

In [2]:
df = pd.read_csv("Salaries.csv")

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1016\91212481.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Salaries.csv")

In [3]:
df.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [4]:
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [5]:
#Number of Columns
len(df.columns)

13

In [6]:
#Number of Rows
len(df)

148654

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

### EDA

In [8]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [9]:
df.columns[(df == "Not Provided").any()]

Index(['EmployeeName', 'BasePay', 'OvertimePay', 'OtherPay', 'Benefits'], dtype='object')

Replace "**Not Provided**" with **NaN** in columns that should contain **numeric values**, then cast those columns to **float**.

In [10]:
df["BasePay"] = df["BasePay"].replace("Not Provided", np.nan)
df["BasePay"] = pd.to_numeric(df["BasePay"])

In [11]:
df["OvertimePay"] = df["OvertimePay"].replace("Not Provided", np.nan)
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"])

In [12]:
df["OtherPay"] = df["OtherPay"].replace("Not Provided", np.nan)
df["OtherPay"] = pd.to_numeric(df["OtherPay"])

In [13]:
df["Benefits"] = df["Benefits"].replace("Not Provided", np.nan)
df["Benefits"] = pd.to_numeric(df["Benefits"])

In [14]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

Exclude rows where all three pay columns (**BasePay,OvertimePay,OtherPay**) are NaN, and rows where BasePay is NaN.

In [15]:
mask = (
    ~(df["BasePay"].isna() &
      df["OvertimePay"].isna() &
      df["OtherPay"].isna())
    & df["BasePay"].notna()
)
df.loc[mask, ["BasePay", "OvertimePay", "OtherPay", "TotalPay"]]

          BasePay  OvertimePay   OtherPay   TotalPay
0       167411.18         0.00  400184.25  567595.43
1       155966.02    245131.88  137811.38  538909.28
2       212739.13    106088.18   16452.60  335279.91
3        77916.00     56120.71  198306.90  332343.61
4       134401.60      9737.00  182234.59  326373.19
...           ...          ...        ...        ...
148645       0.00         0.00       0.00       0.00
148647       0.00         0.00       0.00       0.00
148648       0.00         0.00       0.00       0.00
148649       0.00         0.00       0.00       0.00
148653       0.00         0.00    -618.13    -618.13

[148045 rows x 4 columns]

In [16]:
np.allclose(
    df.loc[mask, "TotalPay"] - (
        df.loc[mask, "OvertimePay"] + df.loc[mask, "OtherPay"]
    ),
    df.loc[mask, "BasePay"],
    equal_nan=True
)

True

Since these columns are related, check how many rows have missing values in all of them.

In [17]:
len(df[["BasePay", "OvertimePay", "OtherPay", "TotalPay"]][(df["BasePay"].isna()) & (df["OvertimePay"].isna()) 
& (df["OtherPay"].isna())])

4

In [18]:
df[(df["BasePay"].isna()) & (df["OvertimePay"].isna()) 
& (df["OtherPay"].isna())]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN

Remove rows where all related salary columns have missing values.

In [19]:
df.dropna(
    subset=["BasePay", "OvertimePay", "OtherPay"],
    how="all",
    inplace=True
)

In [20]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148650
Agency                   0
Status              110531
dtype: int64

#### BasePay

Fill the missing values in **BasePay** using the following formula:

**BasePay = TotalPay − (OtherPay + OvertimePay)**

In [21]:
df[["BasePay", "OvertimePay", "OtherPay", "Benefits" ,"TotalPay", "TotalPayBenefits"]][(df["BasePay"].isna())]

        BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits
81391       NaN          0.0  149934.11      0.00  149934.11         149934.11
84506       NaN          0.0  110485.41  20779.00  110485.41         131264.41
84960       NaN          0.0  120000.00   8841.48  120000.00         128841.48
90525       NaN          0.0  106079.31      0.00  106079.31         106079.31
90786       NaN          0.0   81299.02  23877.53   81299.02         105176.55
...         ...          ...        ...       ...        ...               ...
110526      NaN          0.0      10.67      0.00      10.67             10.67
110527      NaN          0.0       5.56      0.00       5.56              5.56
110528      NaN          0.0       0.00     -2.73       0.00             -2.73
110529      NaN          0.0       0.00     -8.20       0.00             -8.20
110530      NaN          0.0       0.00    -33.89       0.00            -33.89

[605 rows x 6 columns]

In [22]:
df["BasePay"] = df["BasePay"].fillna(
    df["TotalPay"] - (df["OtherPay"] + df["OvertimePay"])
)

In [23]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148650
Agency                   0
Status              110531
dtype: int64

Verify that TotalPay equals the sum of BasePay, OvertimePay, and OtherPay for all rows.

In [24]:
np.allclose(
    df["BasePay"] + df["OvertimePay"] + df["OtherPay"],
    df["TotalPay"],
    equal_nan=True
)

True

#### Benefits

In [25]:
df[["Benefits" ,"TotalPay", "TotalPayBenefits"]][(df["Benefits"].isna())]

       Benefits   TotalPay  TotalPayBenefits
0           NaN  567595.43         567595.43
1           NaN  538909.28         538909.28
2           NaN  335279.91         335279.91
3           NaN  332343.61         332343.61
4           NaN  326373.19         326373.19
...         ...        ...               ...
36154       NaN       4.17              4.17
36155       NaN       0.30              0.30
36156       NaN       0.00              0.00
36157       NaN       0.00              0.00
36158       NaN       0.00              0.00

[36159 rows x 3 columns]

In [26]:
mask_benefit = df["Benefits"].notna()
mask_benefit

0         False
1         False
2         False
3         False
4         False
          ...
148645     True
148647     True
148648     True
148649     True
148653     True
Name: Benefits, Length: 148650, dtype: bool

Verify the relationship between the TotalPay, Benefits, and TotalPayBenefits columns:
**TotalPayBenefits = TotalPay + Benefits**

In [27]:
np.allclose(
    df.loc[mask_benefit,"Benefits"] + df.loc[mask_benefit,"TotalPay"] ,
    df.loc[mask_benefit,"TotalPayBenefits"],
    equal_nan=True
)

True

In [28]:
df["Benefits"] = df["Benefits"].fillna(
    df["TotalPayBenefits"] - df["TotalPay"]
)

In [29]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148650
Agency                   0
Status              110531
dtype: int64

#### Removing Invalid Salary Records

Records with **0** in all salary-related columns (`BasePay`, `OvertimePay`, `OtherPay`, `Benefits`, and `TotalPay`) were considered invalid for salary analysis. These records were identified, removed from the dataset, and the removal was verified.

In [30]:
mask_zero = ((df["BasePay"] == 0) &
        (df["OvertimePay"] == 0) &
        (df["OtherPay"] == 0) &
        (df["TotalPay"] == 0) & 
        (df["Benefits"] == 0) )
len(df[mask_zero])

26

In [31]:
df = df[~(mask_zero)]

In [32]:
len(df[mask_zero])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1016\79172985.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(df[mask_zero])

0

#### Negative Salary Values

Negative values were identified in some salary-related columns. These records were retained because they may reflect payroll adjustments or accounting corrections rather than invalid data.

In [33]:
mask_mins = ((df["BasePay"] < 0) |
        (df["OvertimePay"] < 0) |
        (df["OtherPay"] < 0) |
        (df["TotalPay"] < 0) | 
        (df["Benefits"] < 0) )
len(df[mask_mins])

21

In [34]:
df[["EmployeeName","BasePay","OvertimePay" ,"OtherPay" ,"Benefits" ,"TotalPay", "TotalPayBenefits"]][mask_mins]

,EmployeeName,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits
72832,Irwin Sidharta,-166.01,249.02,0.00,6.56,83.01,89.57
72865,Robert Scott,-121.63,182.70,0.00,5.44,61.07,66.51
72872,Chung Huey Kung,-109.22,163.83,0.00,4.32,54.61,58.93
72874,Jordan Li,-106.60,159.90,0.00,4.66,53.30,57.96
72878,Richard Jackson,-101.88,153.08,0.00,4.55,51.20,55.75
72884,DiMarco McGhee-Stewart,-93.14,139.97,0.00,4.17,46.83,51.00
72888,Leopoldo Marasigan,-87.38,131.06,0.00,3.89,43.68,47.57
72894,Douglas Avalos,-75.67,113.76,0.00,3.39,38.09,41.48
72908,Norma Rodriguez,-59.59,89.65,0.00,2.68,30.06,32.74
72920,Charles Williams,-30.58,45.87,0.00,1.36,15.29,16.65
72922,John Draper,-9.50,14.25,0.00,0.42,4.75,5.17
84969,Pei Meng,101274.51,0.00,-7058.59,34583.40,94215.92,128799.32
90714,Claudia M Sanchez,75033.03,-0.01,1540.00,28864.64,76573.02,105437.66
93200,Jose A Lemus,66744.00,2234.40,-9.60,26889.04,68968.80,95857.84
96168,John G Alexander,59733.32,46.76,-46.76,25863.91,59733.32,85597.23
107184,Amelie E Bullard,6932.50,0.00,-50.19,418.03,6882.31,7300.34
110528,Timothy E Gibson,0.00,0.00,0.00,-2.73,0.00,-2.73
110529,Mark E Laherty,0.00,0.00,0.00,-8.20,0.00,-8.20
110530,David P Kucia,0.00,0.00,0.00,-33.89,0.00,-33.89
144099,Leticia Villacampa,0.00,0.00,9991.77,-13.80,9991.77,9977.97
148653,Joe Lopez,0.00,0.00,-618.13,0.00,-618.13,-618.13

In [35]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148624
Agency                   0
Status              110528
dtype: int64

#### Removing Unnecessary Columns

The `Id`, `Notes`, `Status`, and `Agency` columns were removed because they are not relevant to the objectives of this analysis and do not provide useful information for salary exploration.

In [36]:
df.drop(columns=["Notes","Id","Status","Agency"], inplace=True)

In [37]:
df.describe()

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148624.000000,148624.000000,148624.000000,148624.000000,148624.000000,148624.000000,148624.000000
mean,66067.062342,5066.946133,3649.405605,18928.052727,74783.414081,93711.466808,2012.522406
std,42880.769285,11455.186420,8057.161986,17164.905825,50510.932452,62785.758548,1.117452
min,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,32840.870000,0.000000,0.000000,0.000000,36191.340000,44129.167500,2012.000000
50%,64872.330000,0.000000,812.290000,23236.325000,71432.885000,92417.345000,2013.000000
75%,94611.002500,4658.937500,4237.620000,33470.220000,105848.182500,132884.875000,2014.000000
max,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

In [38]:
df.to_csv("sf_salaries_cleaned.csv", index=False)